/* This is auto-generated code from LDmicro. Do not edit this file! Go
   back to the ladder diagram source for changes in the logic, and make
   any C additions either in ladder.h or in additional .c files linked
   against this one. */

/* You must provide ladder.h; there you must provide:
      * a typedef for SWORD and BOOL, signed 16 bit and boolean types
        (probably typedef signed short SWORD; typedef unsigned char BOOL;)

   You must also provide implementations of all the I/O read/write
   either as inlines in the header file or in another source file. (The
   I/O functions are all declared extern.)

   See the generated source code (below) for function names. */
#include "ladder.h"

/* Define EXTERN_EVERYTHING in ladder.h if you want all symbols extern.
   This could be useful to implement `magic variables,' so that for
   example when you write to the ladder variable duty_cycle, your PLC
   runtime can look at the C variable U_duty_cycle and use that to set
   the PWM duty cycle on the micro. That way you can add support for
   peripherals that LDmicro doesn't know about. */
#ifdef EXTERN_EVERYTHING
#define STATIC 
#else
#define STATIC static
#endif

/* Define NO_PROTOTYPES if you don't want LDmicro to provide prototypes for
   all the I/O functions (Read_U_xxx, Write_U_xxx) that you must provide.
   If you define this then you must provide your own prototypes for these
   functions in ladder.h, or provide definitions (e.g. as inlines or macros)
   for them in ladder.h. */
#ifdef NO_PROTOTYPES
#define PROTO(x)
#else
#define PROTO(x) x
#endif

/* U_xxx symbols correspond to user-defined names. There is such a symbol
   for every internal relay, variable, timer, and so on in the ladder
   program. I_xxx symbols are internally generated. */
STATIC BOOL I_b_mcr = 0;
#define Read_I_b_mcr() I_b_mcr
#define Write_I_b_mcr(x) I_b_mcr = x
STATIC BOOL I_b_rung_top = 0;
#define Read_I_b_rung_top() I_b_rung_top
#define Write_I_b_rung_top(x) I_b_rung_top = x

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XDI1(void);)

STATIC SWORD U_i_TTON1 = 0;

/* You provide these functions. */
PROTO(BOOL Read_U_b_YDO1(void);)
PROTO(void Write_U_b_YDO1(BOOL v);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XDI2(void);)

STATIC BOOL I_b_TTOF1_antiglitch = 0;
#define Read_I_b_TTOF1_antiglitch() I_b_TTOF1_antiglitch
#define Write_I_b_TTOF1_antiglitch(x) I_b_TTOF1_antiglitch = x
STATIC SWORD U_i_TTOF1 = 0;

/* You provide these functions. */
PROTO(BOOL Read_U_b_YDO2(void);)
PROTO(void Write_U_b_YDO2(BOOL v);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XDI3(void);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YDO3(void);)
PROTO(void Write_U_b_YDO3(BOOL v);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XDI4(void);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YDO4(void);)
PROTO(void Write_U_b_YDO4(BOOL v);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XDI5(void);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YDO5(void);)
PROTO(void Write_U_b_YDO5(BOOL v);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XDI6(void);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YDO6(void);)
PROTO(void Write_U_b_YDO6(BOOL v);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XAI1(void);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YAO1(void);)
PROTO(void Write_U_b_YAO1(BOOL v);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XAI2(void);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YAO2(void);)
PROTO(void Write_U_b_YAO2(BOOL v);)



/* Call this function once per PLC cycle. You are responsible for calling
   it at the interval that you specified in the MCU configuration when you
   generated this code. */
void PlcCycle(void)
{
    Write_I_b_mcr(1);
    
    /* start rung 1 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XDI1()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        if(U_i_TTON1 < 4999) {
            U_i_TTON1++;
            Write_I_b_rung_top(0);
        }
    } else {
        U_i_TTON1 = 0;
    }
    
    Write_U_b_YDO1(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 2 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XDI2()) {
        Write_I_b_rung_top(0);
    }
    
    if(!Read_I_b_TTOF1_antiglitch()) {
        U_i_TTOF1 = 1999;
    }
    Write_I_b_TTOF1_antiglitch(1);
    if(!Read_I_b_rung_top()) {
        if(U_i_TTOF1 < 1999) {
            U_i_TTOF1++;
            Write_I_b_rung_top(1);
        }
    } else {
        U_i_TTOF1 = 0;
    }
    
    Write_U_b_YDO2(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 3 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XDI3()) {
        Write_I_b_rung_top(0);
    }
    
    Write_U_b_YDO3(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 4 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XDI4()) {
        Write_I_b_rung_top(0);
    }
    
    Write_U_b_YDO4(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 5 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XDI5()) {
        Write_I_b_rung_top(0);
    }
    
    Write_U_b_YDO5(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 6 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XDI6()) {
        Write_I_b_rung_top(0);
    }
    
    Write_U_b_YDO6(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 7 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XAI1()) {
        Write_I_b_rung_top(0);
    }
    
    Write_U_b_YAO1(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 8 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XAI2()) {
        Write_I_b_rung_top(0);
    }
    
    Write_U_b_YAO2(Read_I_b_rung_top());
    
    /* ] finish series */
}
